name: Release to PyPI

on:
  push:
    tags:
      - "*.*.*"
jobs:
  pypi-publish:
    name: Publish release ${{ github.ref_name}} to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
      - name: Ensure version matches tag
        run: poetry version ${{github.ref_name}}
      - name: Build package
        run: poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Get changelog
        id: changelog
        run: |
          echo "CHANGELOG=$(cz changelog --dry-run ${{github.ref_name}})" >> $GITHUB_OUTPUT
      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.*
          body: ${{steps.changelog.outputs.CHANGELOG}}
